#!/bin/bash
source /home/karthik/code/blog/env/bin/activate
# simple af file watcher
python3 gen.py
# copy images over
cp -r images site/
cp _redirects site/_redirects
while inotifywait -e close_write -r css/ posts/ pages/ misc/; do python gen.py; done
