#!/bin/bash
source /home/karthik/code/heems.github.io/env/bin/activate
# simple af file watcher
python gen.py
# copy images over
cp -r images site/images
while inotifywait -e close_write -r css/ posts/ pages/ misc/; do python gen.py; done
